services:
  bot:
    build: .
    container_name: moba-bot
    restart: unless-stopped
    volumes:
      - ./stats.json:/app/stats.json
      - ./wallet.key:/app/wallet.key:ro
      - ./fleet.json:/app/fleet.json:ro
    environment:
      # alternative to wallet.key file:
      # - WALLET_PK=0x...
      - PYTHONUNBUFFERED=1
