#!/usr/bin/env python3
"""Register your fleet — fresh agent names, optional wallet connect, write fleet.json.

Edit NEW_BOTS below with your own names + lanes + style choices, then run.
The script registers each name via /api/agents/register, optionally connects
your wallet (reads wallet.key or WALLET_PK env var), and writes a populated
fleet.json. ws_runner.py / dashboard.py read fleet.json on the next launch.

Run:  python3 register.py
"""

from __future__ import annotations
import json, os, shutil, sys, time
from datetime import datetime
import requests

DIR = os.path.dirname(os.path.abspath(__file__))
BASE = "https://wc2-agentic-dev-3o6un.ondigitalocean.app"
FLEET = os.path.join(DIR, "fleet.json")

# --- EDIT THIS LIST ---------------------------------------------------------
# Names must be unique across the server. If you get a 409 on register,
# pick different names. style options: "lmeow" (passive farm) or "sigma"
# (field-aware lane switching — recommended). ability_prio is the upgrade
# pick order: fireball-first works best for kill credit on mages.
NEW_BOTS = [
    {
        "name": "MyBot_Top",   "class": "mage", "lane": "top", "role": "mage",
        "style": "sigma",
        "ability_prio": ["fireball", "tornado", "fortitude", "fury", "raise_skeleton"],
        "wallet": True,
        "skin": "pixagreen_mage",   # remove this line if you don't own the NFT
    },
    {
        "name": "MyBot_Mid",   "class": "mage", "lane": "mid", "role": "mage",
        "style": "sigma",
        "ability_prio": ["fireball", "tornado", "fortitude", "fury", "raise_skeleton"],
        "wallet": True,
        "skin": "pixagreen_mage",
    },
    {
        "name": "MyBot_Bot",   "class": "mage", "lane": "bot", "role": "mage",
        "style": "sigma",
        "ability_prio": ["fireball", "tornado", "fortitude", "fury", "raise_skeleton"],
        "wallet": True,
        "skin": "pixagreen_mage",
        "rotate_lane": True,        # round-robin top->mid->bot across games
    },
]
# ---------------------------------------------------------------------------


def register(name: str) -> str | None:
    r = requests.post(f"{BASE}/api/agents/register",
                      json={"agentName": name}, timeout=10)
    if r.status_code == 201:
        d = r.json()
        return d.get("apiKey") or d.get("api_key") or d.get("key")
    if r.status_code == 409:
        print(f"  [!] {name}: name already taken — pick a different one.")
        return None
    print(f"  [!] {name}: register failed {r.status_code} {r.text[:160]}")
    return None


def main():
    if os.path.exists(FLEET):
        try:
            cur = json.load(open(FLEET))
            cur_names = {b.get("name") for b in cur.get("bots", [])}
            dup = [b["name"] for b in NEW_BOTS if b["name"] in cur_names]
            if dup:
                print(f"[!] fleet.json already has {dup}. Abort.")
                sys.exit(1)
        except Exception:
            pass

    print(f"Registering {len(NEW_BOTS)} agents...")
    keys: list[str] = []
    for b in NEW_BOTS:
        print(f"  register {b['name']}...")
        k = register(b["name"])
        if not k:
            print("\nAborting. No fleet.json changes made.")
            sys.exit(1)
        keys.append(k)
        time.sleep(0.3)
    for b, k in zip(NEW_BOTS, keys):
        b["key"] = k
    print("  all registered.")

    from wallet import load_pk, connect_bot
    pk = load_pk()
    if not pk:
        print("[!] No WALLET_PK or wallet.key found — skipping wallet connect.")
    else:
        print("Connecting wallet to each agent...")
        for b in NEW_BOTS:
            r = connect_bot(b["name"], b["key"], pk)
            if "error" in r:
                print(f"  [!] {b['name']}: {r['error']}")
            else:
                print(f"  {b['name']}: holder={r.get('tokenHolder')} "
                      f"pixagreenMage={r.get('pixagreenMage')}")

    if os.path.exists(FLEET):
        ts = datetime.now().strftime("%Y-%m-%dT%H%M%S")
        archive = os.path.join(DIR, f"fleet.archive-{ts}.json")
        shutil.copy2(FLEET, archive)
        print(f"Archived prior fleet -> {os.path.basename(archive)}")

    old = {}
    if os.path.exists(FLEET):
        try: old = json.load(open(FLEET))
        except Exception: pass
    new_fleet = {
        "game": old.get("game", 3),
        "notes": "Generated by register.py",
        "bots": NEW_BOTS,
    }
    with open(FLEET, "w") as f:
        json.dump(new_fleet, f, indent=2)
    print(f"\nWrote new fleet.json. {len(NEW_BOTS)} bots configured.")
    print("\nNext: python3 dashboard.py")


if __name__ == "__main__":
    main()
