#!/usr/bin/env python3
"""Register your fleet — v3 build with per-lane ability priorities.

Edit NEW_BOTS with your own names. Each bot has a lane-specific prio that
matches what the controller's three-phase ability picker (kill-execute /
breadth-first / upgrade-order) is tuned for:
  - mid:   fireball-first (kill execution)
  - top:   fortitude-first (attrition lane, survive longer)
  - bot:   tornado-first (AoE pressure on solo lane)
  - rotate: tornado-first (multi-lane fights)

Order matters — the bot at index 0 registers + wallet-connects FIRST,
which can matter for any first-come-first-served NFT equip behavior.

Run:  python3 register.py
"""

from __future__ import annotations
import json, os, shutil, sys, time
from datetime import datetime
import requests

DIR = os.path.dirname(os.path.abspath(__file__))
BASE = "https://wc2-agentic-dev-3o6un.ondigitalocean.app"
FLEET = os.path.join(DIR, "fleet.json")

NEW_BOTS = [
    {"name": "MyBot_Carry", "class": "mage", "lane": "mid", "role": "mage",
     "style": "sigma",
     "ability_prio": ["fireball", "tornado", "fortitude", "fury", "raise_skeleton"],
     "wallet": True, "skin": "pixagreen_mage"},
    {"name": "MyBot_Top", "class": "mage", "lane": "top", "role": "mage",
     "style": "sigma",
     "ability_prio": ["fortitude", "fireball", "tornado", "fury", "raise_skeleton"],
     "wallet": True, "skin": "pixagreen_mage"},
    {"name": "MyBot_Bot", "class": "mage", "lane": "bot", "role": "mage",
     "style": "sigma",
     "ability_prio": ["tornado", "fireball", "fortitude", "fury", "raise_skeleton"],
     "wallet": True, "skin": "pixagreen_mage"},
    {"name": "MyBot_Rot", "class": "mage", "lane": "top", "role": "mage",
     "style": "sigma",
     "ability_prio": ["tornado", "fireball", "fortitude", "fury", "raise_skeleton"],
     "wallet": True, "skin": "pixagreen_mage", "rotate_lane": True},
]


def register(name):
    r = requests.post(f"{BASE}/api/agents/register",
                      json={"agentName": name}, timeout=10)
    if r.status_code == 201:
        d = r.json()
        return d.get("apiKey") or d.get("api_key") or d.get("key")
    if r.status_code == 409:
        print(f"  [!] {name}: name already taken — pick a different one.")
        return None
    print(f"  [!] {name}: register failed {r.status_code} {r.text[:160]}")
    return None


def main():
    if os.path.exists(FLEET):
        try:
            cur = json.load(open(FLEET))
            cur_names = {b.get("name") for b in cur.get("bots", [])}
            dup = [b["name"] for b in NEW_BOTS if b["name"] in cur_names]
            if dup:
                print(f"[!] fleet.json already has {dup}. Abort.")
                sys.exit(1)
        except Exception:
            pass

    print(f"Registering {len(NEW_BOTS)} agents (index 0 first)...")
    keys = []
    for b in NEW_BOTS:
        print(f"  register {b['name']}...")
        k = register(b["name"])
        if not k:
            print("\nAborting. No fleet.json changes made.")
            sys.exit(1)
        keys.append(k)
        time.sleep(0.3)
    for b, k in zip(NEW_BOTS, keys):
        b["key"] = k
    print("  all registered.")

    from wallet import load_pk, connect_bot
    pk = load_pk()
    if not pk:
        print("[!] No WALLET_PK / wallet.key — skipping wallet connect.")
    else:
        print("Connecting wallet to each agent...")
        for b in NEW_BOTS:
            r = connect_bot(b["name"], b["key"], pk)
            if "error" in r:
                print(f"  [!] {b['name']}: {r['error']}")
            else:
                perks = {k: v for k, v in r.items()
                         if k not in ("message", "address", "tokenBalance")}
                print(f"  {b['name']}: {perks}")

    if os.path.exists(FLEET):
        ts = datetime.now().strftime("%Y-%m-%dT%H%M%S")
        archive = os.path.join(DIR, f"fleet.archive-{ts}.json")
        shutil.copy2(FLEET, archive)
        print(f"Archived prior fleet -> {os.path.basename(archive)}")

    old = {}
    if os.path.exists(FLEET):
        try: old = json.load(open(FLEET))
        except Exception: pass
    new_fleet = {
        "game": old.get("game", 3),
        "notes": "Generated by register.py — v3 4-bot squad with per-lane ability_prio",
        "bots": NEW_BOTS,
    }
    with open(FLEET, "w") as f:
        json.dump(new_fleet, f, indent=2)
    print(f"\nWrote new fleet.json. {len(NEW_BOTS)} bots configured.")
    print("\nNext: python3 dashboard.py")
    print("(fresh-game gate in ws_runner waits for the next game-start before deploying)")


if __name__ == "__main__":
    main()
